// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_COMPILED_CIRCUIT_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_COMPILED_CIRCUIT_VALIDATION
int8_t uniffi_ezkl_fn_func_compiled_circuit_validation(RustBuffer compiled_circuit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_ENCODE_VERIFIER_CALLDATA
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_ENCODE_VERIFIER_CALLDATA
RustBuffer uniffi_ezkl_fn_func_encode_verifier_calldata(RustBuffer proof, RustBuffer vk_address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_PK
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_PK
RustBuffer uniffi_ezkl_fn_func_gen_pk(RustBuffer vk, RustBuffer compiled_circuit, RustBuffer srs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_VK
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_VK
RustBuffer uniffi_ezkl_fn_func_gen_vk(RustBuffer compiled_circuit, RustBuffer srs, int8_t compress_selectors, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_WITNESS
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_GEN_WITNESS
RustBuffer uniffi_ezkl_fn_func_gen_witness(RustBuffer compiled_circuit, RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_INPUT_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_INPUT_VALIDATION
int8_t uniffi_ezkl_fn_func_input_validation(RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PK_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PK_VALIDATION
int8_t uniffi_ezkl_fn_func_pk_validation(RustBuffer pk, RustBuffer settings, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PROOF_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PROOF_VALIDATION
int8_t uniffi_ezkl_fn_func_proof_validation(RustBuffer proof, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PROVE
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_PROVE
RustBuffer uniffi_ezkl_fn_func_prove(RustBuffer witness, RustBuffer pk, RustBuffer compiled_circuit, RustBuffer srs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_SETTINGS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_SETTINGS_VALIDATION
int8_t uniffi_ezkl_fn_func_settings_validation(RustBuffer settings, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_SRS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_SRS_VALIDATION
int8_t uniffi_ezkl_fn_func_srs_validation(RustBuffer srs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VERIFY
int8_t uniffi_ezkl_fn_func_verify(RustBuffer proof, RustBuffer vk, RustBuffer settings, RustBuffer srs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VERIFY_AGGR
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VERIFY_AGGR
int8_t uniffi_ezkl_fn_func_verify_aggr(RustBuffer proof_js, RustBuffer vk, uint64_t logrows, RustBuffer srs, RustBuffer commitment, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VK_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_VK_VALIDATION
int8_t uniffi_ezkl_fn_func_vk_validation(RustBuffer vk, RustBuffer settings, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_WITNESS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_FN_FUNC_WITNESS_VALIDATION
int8_t uniffi_ezkl_fn_func_witness_validation(RustBuffer witness, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_ALLOC
RustBuffer ffi_ezkl_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ezkl_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_FREE
void ffi_ezkl_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_EZKL_RUSTBUFFER_RESERVE
RustBuffer ffi_ezkl_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U8
void ffi_ezkl_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U8
void ffi_ezkl_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U8
void ffi_ezkl_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ezkl_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I8
void ffi_ezkl_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I8
void ffi_ezkl_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I8
void ffi_ezkl_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ezkl_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U16
void ffi_ezkl_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U16
void ffi_ezkl_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U16
void ffi_ezkl_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ezkl_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I16
void ffi_ezkl_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I16
void ffi_ezkl_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I16
void ffi_ezkl_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ezkl_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U32
void ffi_ezkl_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U32
void ffi_ezkl_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U32
void ffi_ezkl_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ezkl_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I32
void ffi_ezkl_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I32
void ffi_ezkl_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I32
void ffi_ezkl_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ezkl_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_U64
void ffi_ezkl_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_U64
void ffi_ezkl_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_U64
void ffi_ezkl_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ezkl_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_I64
void ffi_ezkl_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_I64
void ffi_ezkl_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_I64
void ffi_ezkl_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ezkl_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_F32
void ffi_ezkl_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_F32
void ffi_ezkl_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_F32
void ffi_ezkl_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_F32
float ffi_ezkl_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_F64
void ffi_ezkl_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_F64
void ffi_ezkl_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_F64
void ffi_ezkl_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_F64
double ffi_ezkl_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_POINTER
void ffi_ezkl_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_POINTER
void ffi_ezkl_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_POINTER
void ffi_ezkl_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_ezkl_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ezkl_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ezkl_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ezkl_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ezkl_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_POLL_VOID
void ffi_ezkl_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_CANCEL_VOID
void ffi_ezkl_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_FREE_VOID
void ffi_ezkl_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_EZKL_RUST_FUTURE_COMPLETE_VOID
void ffi_ezkl_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_COMPILED_CIRCUIT_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_COMPILED_CIRCUIT_VALIDATION
uint16_t uniffi_ezkl_checksum_func_compiled_circuit_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_ENCODE_VERIFIER_CALLDATA
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_ENCODE_VERIFIER_CALLDATA
uint16_t uniffi_ezkl_checksum_func_encode_verifier_calldata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_PK
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_PK
uint16_t uniffi_ezkl_checksum_func_gen_pk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_VK
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_VK
uint16_t uniffi_ezkl_checksum_func_gen_vk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_WITNESS
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_GEN_WITNESS
uint16_t uniffi_ezkl_checksum_func_gen_witness(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_INPUT_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_INPUT_VALIDATION
uint16_t uniffi_ezkl_checksum_func_input_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PK_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PK_VALIDATION
uint16_t uniffi_ezkl_checksum_func_pk_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PROOF_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PROOF_VALIDATION
uint16_t uniffi_ezkl_checksum_func_proof_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PROVE
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_PROVE
uint16_t uniffi_ezkl_checksum_func_prove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_SETTINGS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_SETTINGS_VALIDATION
uint16_t uniffi_ezkl_checksum_func_settings_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_SRS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_SRS_VALIDATION
uint16_t uniffi_ezkl_checksum_func_srs_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VERIFY
uint16_t uniffi_ezkl_checksum_func_verify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VERIFY_AGGR
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VERIFY_AGGR
uint16_t uniffi_ezkl_checksum_func_verify_aggr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VK_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_VK_VALIDATION
uint16_t uniffi_ezkl_checksum_func_vk_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_WITNESS_VALIDATION
#define UNIFFI_FFIDEF_UNIFFI_EZKL_CHECKSUM_FUNC_WITNESS_VALIDATION
uint16_t uniffi_ezkl_checksum_func_witness_validation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EZKL_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_EZKL_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ezkl_uniffi_contract_version(void
    
);
#endif

